[package]
authors = ["Christian Legaard <clegaard@outlook.com>"]
edition = "2018"
name = "unifmu"
version = "0.0.1"


[dependencies]

clap = "*"

libc = "*"
lazy_static = "*"
log = "*"
num_enum = "*"
env_logger = "*"
fs_extra = "*"
structopt = "*"
tempfile = "*"
rust-embed = "6.0.0"
