[package]
authors = ["Christian Legaard <clegaard@outlook.com>"]
edition = "2018"
name = "unifmu"
version = "0.0.4"

[dependencies]

clap = "*"
env_logger = "*"
fs_extra = "*"
lazy_static = "*"
libc = "*"
libloading = "*"
log = "*"
num_enum = "*"
rust-embed = "6.0.0"
structopt = "*"
tempfile = "*"
url = "*"
