[package]
authors = ["Christian Legaard <clegaard@outlook.com>"]
edition = "2018"
name = "unifmu"
version = "0.0.5"

[dependencies]

clap = "*"
env_logger = "*"
fs_extra = "*"
lazy_static = "*"
libc = "*"
dlopen = "*"
dlopen_derive = "*"
log = "*"
num_enum = "*"
rust-embed = "6.0.0"
structopt = "*"
tempfile = "*"
url = "*"
walkdir = "*"
zip = { version = "*", default-features = false, features = ["deflate"] }

common = { path = "../common" }
