[package]
authors = ["Christian Legaard <clegaard@outlook.com>"]
edition = "2021"
name = "unifmu"
version = "0.0.7"

[dependencies]

clap = { version = "3.0.14", features = ["derive"] }
dlopen = "*"
dlopen_derive = "*"
env_logger = "*"
fs_extra = "*"
lazy_static = "*"
libc = "*"
log = "*"
num_enum = "*"
rust-embed = "6.0.0"
tempfile = "*"
url = "*"
walkdir = "*"
zip = { version = "*", default-features = false, features = ["deflate"] }

common = { path = "../common" }
