FROM python:3.8

RUN pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY modelDescription.xml modelDescription.xml

WORKDIR resources
COPY src .

ENTRYPOINT [ "python", "backend_schemaless_rpc.py" ]