active_dispatcher = "socket"

[socket]
type = "zmq"
format = "pickle"
linux = ["python3", "backend_schemaless_rpc.py"]
macos = ["python3", "backend_schemaless_rpc.py"]
windows = ["python", "backend_schemaless_rpc.py"]

[grpc]
linux = ["python3", "backend_grpc.py"]
macos = ["python3", "backend_grpc.py"]
windows = ["python", "backend_grpc.py"]
