active_dispatcher = "socket"

[socket]
type = "zmq"
format = "json"
linux = ["python3", "socket_slave.py"]
macos = ["python3", "socket_slave.py"]
windows = ["python", "socket_slave.py"]

[grpc]
linux = ["python3", "backend_grpc.py"]
macos = ["python3", "backend_grpc.py"]
windows = ["python", "backend_grpc.py"]
