linux = ["java", "--jar", "target/unifmu-0.0.1-jar-with-dependencies.jar"]
macos = ["java", "--jar", "target/unifmu-0.0.1-jar-with-dependencies.jar"]
windows = ["java", "--jar", "target/unifmu-0.0.1-jar-with-dependencies.jar"]
