// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class DeserializeArgs extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static DeserializeArgs getRootAsDeserializeArgs(ByteBuffer _bb) { return getRootAsDeserializeArgs(_bb, new DeserializeArgs()); }
  public static DeserializeArgs getRootAsDeserializeArgs(ByteBuffer _bb, DeserializeArgs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DeserializeArgs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte state(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int stateLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector stateVector() { return stateVector(new ByteVector()); }
  public ByteVector stateVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer stateAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer stateInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createDeserializeArgs(FlatBufferBuilder builder,
      int stateOffset) {
    builder.startTable(1);
    DeserializeArgs.addState(builder, stateOffset);
    return DeserializeArgs.endDeserializeArgs(builder);
  }

  public static void startDeserializeArgs(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addState(FlatBufferBuilder builder, int stateOffset) { builder.addOffset(0, stateOffset, 0); }
  public static int createStateVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createStateVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startStateVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endDeserializeArgs(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // state
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DeserializeArgs get(int j) { return get(new DeserializeArgs(), j); }
    public DeserializeArgs get(DeserializeArgs obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

