// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers;

public final class Fmi2Status {
  private Fmi2Status() { }
  public static final int Ok = 0;
  public static final int Warning = 1;
  public static final int Discard = 2;
  public static final int Error = 3;
  public static final int Fatal = 4;
  public static final int Pending = 5;

  public static final String[] names = { "Ok", "Warning", "Discard", "Error", "Fatal", "Pending", };

  public static String name(int e) { return names[e]; }
}

