// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers;

public final class Fmi2CommandArg {
  private Fmi2CommandArg() { }
  public static final byte NONE = 0;
  public static final byte SetDebugLoggingArgs = 1;
  public static final byte SetupExperimentArgs = 2;
  public static final byte FreeInstanceArgs = 3;
  public static final byte EnterInitializationModeArgs = 4;
  public static final byte ExitInitializationModeArgs = 5;
  public static final byte TerminateArgs = 6;
  public static final byte ResetArgs = 7;
  public static final byte SetRealArgs = 8;
  public static final byte SetIntegerArgs = 9;
  public static final byte SetBooleanArgs = 10;
  public static final byte SetStringArgs = 11;
  public static final byte GetRealArgs = 12;
  public static final byte GetIntegerArgs = 13;
  public static final byte GetBooleanArgs = 14;
  public static final byte GetStringArgs = 15;
  public static final byte SerializeArgs = 16;
  public static final byte DeserializeArgs = 17;
  public static final byte GetDirectionalDerivativesArgs = 18;
  public static final byte SetInputDerivativesArgs = 19;
  public static final byte GetOutputDerivitivesArgs = 20;
  public static final byte DoStepArgs = 21;
  public static final byte CancelStepArgs = 22;
  public static final byte GetXXXStatusArgs = 23;

  public static final String[] names = { "NONE", "SetDebugLoggingArgs", "SetupExperimentArgs", "FreeInstanceArgs", "EnterInitializationModeArgs", "ExitInitializationModeArgs", "TerminateArgs", "ResetArgs", "SetRealArgs", "SetIntegerArgs", "SetBooleanArgs", "SetStringArgs", "GetRealArgs", "GetIntegerArgs", "GetBooleanArgs", "GetStringArgs", "SerializeArgs", "DeserializeArgs", "GetDirectionalDerivativesArgs", "SetInputDerivativesArgs", "GetOutputDerivitivesArgs", "DoStepArgs", "CancelStepArgs", "GetXXXStatusArgs", };

  public static String name(int e) { return names[e]; }
}

