// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GetBooleanReturn extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static GetBooleanReturn getRootAsGetBooleanReturn(ByteBuffer _bb) { return getRootAsGetBooleanReturn(_bb, new GetBooleanReturn()); }
  public static GetBooleanReturn getRootAsGetBooleanReturn(ByteBuffer _bb, GetBooleanReturn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetBooleanReturn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int status() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean values(int j) { int o = __offset(6); return o != 0 ? 0!=bb.get(__vector(o) + j * 1) : false; }
  public int valuesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public BooleanVector valuesVector() { return valuesVector(new BooleanVector()); }
  public BooleanVector valuesVector(BooleanVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer valuesAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer valuesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createGetBooleanReturn(FlatBufferBuilder builder,
      int status,
      int valuesOffset) {
    builder.startTable(2);
    GetBooleanReturn.addValues(builder, valuesOffset);
    GetBooleanReturn.addStatus(builder, status);
    return GetBooleanReturn.endGetBooleanReturn(builder);
  }

  public static void startGetBooleanReturn(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addStatus(FlatBufferBuilder builder, int status) { builder.addInt(0, status, 0); }
  public static void addValues(FlatBufferBuilder builder, int valuesOffset) { builder.addOffset(1, valuesOffset, 0); }
  public static int createValuesVector(FlatBufferBuilder builder, boolean[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addBoolean(data[i]); return builder.endVector(); }
  public static void startValuesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endGetBooleanReturn(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GetBooleanReturn get(int j) { return get(new GetBooleanReturn(), j); }
    public GetBooleanReturn get(GetBooleanReturn obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

