// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GetIntegerReturn extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static GetIntegerReturn getRootAsGetIntegerReturn(ByteBuffer _bb) { return getRootAsGetIntegerReturn(_bb, new GetIntegerReturn()); }
  public static GetIntegerReturn getRootAsGetIntegerReturn(ByteBuffer _bb, GetIntegerReturn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetIntegerReturn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int status() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int values(int j) { int o = __offset(6); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int valuesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public IntVector valuesVector() { return valuesVector(new IntVector()); }
  public IntVector valuesVector(IntVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer valuesAsByteBuffer() { return __vector_as_bytebuffer(6, 4); }
  public ByteBuffer valuesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 4); }

  public static int createGetIntegerReturn(FlatBufferBuilder builder,
      int status,
      int valuesOffset) {
    builder.startTable(2);
    GetIntegerReturn.addValues(builder, valuesOffset);
    GetIntegerReturn.addStatus(builder, status);
    return GetIntegerReturn.endGetIntegerReturn(builder);
  }

  public static void startGetIntegerReturn(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addStatus(FlatBufferBuilder builder, int status) { builder.addInt(0, status, 0); }
  public static void addValues(FlatBufferBuilder builder, int valuesOffset) { builder.addOffset(1, valuesOffset, 0); }
  public static int createValuesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startValuesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endGetIntegerReturn(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GetIntegerReturn get(int j) { return get(new GetIntegerReturn(), j); }
    public GetIntegerReturn get(GetIntegerReturn obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

