// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SetDebugLoggingArgs extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static SetDebugLoggingArgs getRootAsSetDebugLoggingArgs(ByteBuffer _bb) { return getRootAsSetDebugLoggingArgs(_bb, new SetDebugLoggingArgs()); }
  public static SetDebugLoggingArgs getRootAsSetDebugLoggingArgs(ByteBuffer _bb, SetDebugLoggingArgs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SetDebugLoggingArgs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String categories(int j) { int o = __offset(4); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int categoriesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public StringVector categoriesVector() { return categoriesVector(new StringVector()); }
  public StringVector categoriesVector(StringVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public boolean loggingOn() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createSetDebugLoggingArgs(FlatBufferBuilder builder,
      int categoriesOffset,
      boolean logging_on) {
    builder.startTable(2);
    SetDebugLoggingArgs.addCategories(builder, categoriesOffset);
    SetDebugLoggingArgs.addLoggingOn(builder, logging_on);
    return SetDebugLoggingArgs.endSetDebugLoggingArgs(builder);
  }

  public static void startSetDebugLoggingArgs(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addCategories(FlatBufferBuilder builder, int categoriesOffset) { builder.addOffset(0, categoriesOffset, 0); }
  public static int createCategoriesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCategoriesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addLoggingOn(FlatBufferBuilder builder, boolean loggingOn) { builder.addBoolean(1, loggingOn, false); }
  public static int endSetDebugLoggingArgs(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SetDebugLoggingArgs get(int j) { return get(new SetDebugLoggingArgs(), j); }
    public SetDebugLoggingArgs get(SetDebugLoggingArgs obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

