// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StatusReturn extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StatusReturn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int status() { return bb.getInt(bb_pos + 0); }

  public static int createStatusReturn(FlatBufferBuilder builder, int status) {
    builder.prep(4, 4);
    builder.putInt(status);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StatusReturn get(int j) { return get(new StatusReturn(), j); }
    public StatusReturn get(StatusReturn obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

