version: "3.9"
services:
    python:
        image: ${UNIFMU_GUID}
        build: .
        command: python backend.py 
        environment: 
            - UNIFMU_GUID
            - UNIFMU_INSTANCE_NAME
            - UNIFMU_VISIBLE
            - UNIFMU_DISPATCHER_ENDPOINT
            - UNIFMU_REFS_TO_ATTRS
        network_mode: host
