backend = "grpc"

[command.grpc]
linux = ["python3", "deploy.sh"]
macos = ["python3", "deploy.sh"]
windows = ["python", "deploy.ps1"]

[command.zmq]
linux = ["python3", "deploy.sh"]
macos = ["python3", "deploy.sh"]
serialization_format = "Pickle"
windows = ["python", "deploy.sh"]
