backend = "grpc"

[grpc]
linux = ["/bin/bash", "deploy.sh"]
macos = ["/bin/bash", "deploy.sh"]
windows = ["powershell", ".\\deploy.ps1"]

[zmq]
linux = ["/bin/bash", "deploy.sh"]
macos = ["/bin/bash", "deploy.sh"]
serialization_format = "Pickle"
windows = ["powershell", ".\\deploy.ps1"]
