# This file defines which files should be copied over when generating a new FMU.
# For each backend a "files" attribute MUST specify which resources to copy over to the FMU.
#
# GLOBS are NOT currently supported
#
# ALL files in the tool/unifmu/resources are available as the "source" side of the command.
# source paths are relative to this directory, whereas destionation paths are relative to the FMU's root

[backend.empty]
files = [
    ["common/unifmu_binaries/win64/unifmu.dll","binaries/win64/unifmu.dll"],
    ["common/unifmu_binaries/linux64/unifmu.so","binaries/linux64/unifmu.so"],
    ["backends/empty/launch.toml","resources/launch.toml"],
]

[backend.python]

files = [
    ["common/unifmu_binaries/win64/unifmu.dll","binaries/win64/unifmu.dll"],
    ["common/unifmu_binaries/linux64/unifmu.so","binaries/linux64/unifmu.so"],
    ["backends/python_fmu/adder.py","resources/adder.py"], 
    ["backends/python_fmu/fmi2.py","resources/fmi2.py"], 
    ["backends/python_fmu/fmi2.py","resources/fmi2.py"],
    ["backends/python_fmu/launch.py","resources/launch.py"], 
    ["backends/python_fmu/launch.toml","resources/launch.toml"],
    ["backends/python_fmu/modelDescription.xml","modelDescription.xml"],
]
