# This file defines which files should be copied over when generating a new FMU.
# For each backend a "files" attribute MUST specify which resources to copy over to the FMU.
#
# GLOBS are NOT currently supported
#
# ALL files in the tool/unifmu/resources are available as the "source" side of the command.
# source paths are relative to this directory, whereas destionation paths are relative to the FMU's root

[backend.empty]
files = [
  ["common/unifmu_binaries/win64/unifmu.dll", "binaries/win64/unifmu.dll"],
  ["common/unifmu_binaries/linux64/unifmu.so", "binaries/linux64/unifmu.so"],
  ["common/unifmu_binaries/darwin64/unifmu.dylib", "binaries/darwin64/unifmu.dylib"],
  ["backends/empty/launch.toml", "resources/launch.toml"],
]

[backend.python_schemaless_rpc]

files = [
  ["common/unifmu_binaries/win64/unifmu.dll", "binaries/win64/unifmu.dll"],
  ["common/unifmu_binaries/linux64/unifmu.so", "binaries/linux64/unifmu.so"],
  ["common/unifmu_binaries/darwin64/unifmu.dylib", "binaries/darwin64/unifmu.dylib"],
  ["backends/python/adder.py", "resources/adder.py"],
  ["backends/python/fmi2.py", "resources/fmi2.py"],
  ["backends/python/backend_schemaless_rpc.py", "resources/backend_schemaless_rpc.py"],
  ["backends/python/launch_schemaless_rpc.toml", "resources/launch.toml"],
  ["common/modelDescription.xml", "modelDescription.xml"],
]

[backend.python_grpc]
files = [
  ["common/unifmu_binaries/win64/unifmu.dll", "binaries/win64/unifmu.dll"],
  ["common/unifmu_binaries/linux64/unifmu.so", "binaries/linux64/unifmu.so"],
  ["common/unifmu_binaries/darwin64/unifmu.dylib", "binaries/darwin64/unifmu.dylib"],
  ["backends/python/adder.py", "resources/adder.py"],
  ["backends/python/fmi2.py", "resources/fmi2.py"],
  ["backends/python/backend_grpc.py", "resources/backend_grpc.py"],
  ["backends/python/schemas/unifmu_fmi2_pb2.py", "resources/schemas/unifmu_fmi2_pb2.py"],
  ["backends/python/schemas/unifmu_fmi2_pb2_grpc.py", "resources/schemas/unifmu_fmi2_pb2_grpc.py"],
  ["backends/python/launch_grpc.toml", "resources/launch.toml"],
  ["common/modelDescription.xml", "modelDescription.xml"],
]

# [backend.csharp]

# files = [
#   ["common/unifmu_binaries/win64/unifmu.dll", "binaries/win64/unifmu.dll"],
#   ["common/unifmu_binaries/linux64/unifmu.so", "binaries/linux64/unifmu.so"],
#   ["common/unifmu_binaries/darwin64/unifmu.dylib", "binaries/darwin64/unifmu.dylib"],
#   ["backends/csharp/launch.toml", "resources/launch.toml"],
#   ["common/modelDescription.xml", "modelDescription.xml"],
# ]

# [backend.java]

# files = [
#   ["common/unifmu_binaries/win64/unifmu.dll", "binaries/win64/unifmu.dll"],
#   ["common/unifmu_binaries/linux64/unifmu.so", "binaries/linux64/unifmu.so"],
#   ["common/unifmu_binaries/darwin64/unifmu.dylib", "binaries/darwin64/unifmu.dylib"],
#   ["backends/java/launch.toml", "resources/launch.toml"],
#   ["backends/java/pom.xml", "resources/pom.xml"],
#   ["backends/java/build.ps1", "resources/build.ps1"],
#   ["backends/java/build.sh", "resources/build.sh"],
#   ["common/modelDescription.xml", "modelDescription.xml"],
# ]

# dirs = [
#   ["backends/java/src", "resources/src"],
# ]
