name: Build and update wrappers

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-wrapper-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7] #[3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install python packages
        run: |
          pip install setuptools
          pip install .[protobuf-schema-generation,python-backend]
          pip install --upgrade protobuf
      - name: Build wrapper
        run: |
          python build.py --update-wrapper
      - name: Update protobuf schemas
        run: |
          python build.py --update-schemas
      - name: run integration tests
        run: |
          python build.py --test-integration
      - name: commit win64 wrapper to repo
        if: github.ref == 'refs/heads/master'
        run: |
          python build.py --github-update-wrapper

  build-wrapper-linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6] #[3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install python packages
        run: |
          pip3 install setuptools
          pip3 install .[protobuf-schema-generation,python-backend]
          pip3 install --upgrade protobuf
      - name: Build wrapper
        run: |
          python3 build.py --update-wrapper
      - name: Update protobuf schemas
        run: |
          python3 build.py --update-schemas
      - name: run integration tests
        run: |
          python3 build.py --test-integration
      - name: commit linux64 wrapper to repo
        if: github.ref == 'refs/heads/master'
        run: |
          python3 build.py --github-update-wrapper

  build-wrapper-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7] #[3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install python packages
        run: |
          pip3 install setuptools
          pip3 install .[protobuf-schema-generation,python-backend]
          pip3 install --upgrade protobuf
      - name: Build wrapper
        run: |
          python3 build.py --update-wrapper
      - name: Update protobuf schemas
        run: |
          python3 build.py --update-schemas
      - name: run integration tests
        run: |
          python3 build.py --test-integration
      - name: commit darwin64 wrapper to repo
        if: github.ref == 'refs/heads/master'
        run: |
          python3 build.py --github-update-wrapper
