# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and update wrappers

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-wrapper-windows:
    runs-on: windows-latest

    steps:
      - name: Install package
        run: |
          pip install .[dev]
      - name: Build wrapper and update examples
        run: |
          python build.py --update-wrapper
      - name: Run integration tests
        run: |
          python build.py --test-c

  build-wrapper-linux:
    runs-on: windows-latest

    steps:
      - name: Install package
        run: |
          pip install .[dev]
      - name: Build wrapper and update examples
        run: |
          python build.py --update-wrapper
      - name: Run integration tests
        run: |
          python build.py --test-c
