name: Build and update wrappers

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-wrapper-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7] #[3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Install python packages
        run: |
          pip install setuptools
          pip install .[protobuf-schema-generation,python-backend]
          pip install --upgrade protobuf
      - name: Build wrapper
        run: |
          python build.py --update-wrapper
      - name: Update protobuf schemas
        run: |
          python build.py --update-schemas
      - name: run integration tests
        run: |
          python3 build.py --test-integration

  build-wrapper-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7] #[3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Install python packages
        run: |
          pip3 install setuptools
          pip3 install .[protobuf-schema-generation,python-backend]
          pip3 install --upgrade protobuf
      - name: Build wrapper
        run: |
          python3 build.py --update-wrapper
      - name: Update protobuf schemas
        run: |
          python3 build.py --update-schemas
      - name: run integration tests
        run: |
          python3 build.py --test-integration

  build-wrapper-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7] #[3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Install python packages
        run: |
          pip3 install setuptools
          pip3 install .[protobuf-schema-generation,python-backend]
          pip3 install --upgrade protobuf
      - name: Build wrapper
        run: |
          python build.py --update-wrapper
      - name: Update protobuf schemas
        run: |
          python build.py --update-schemas
      - name: run integration tests
        run: |
          python3 build.py --test-integration
