# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and update wrappers

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # build-wrapper-windows:
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       python-version: [3.7] #[3.5, 3.6, 3.7, 3.8, 3.9]

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install package
  #       run: |
  #         pip install setuptools
  #         pip install .[dev]
  #     - name: Build wrapper
  #       run: |
  #         python build.py --update-wrapper
  #     - name: Run integration tests
  #       run: |
  #         python build.py --test-integration

  build-wrapper-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7] #[3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Install package
        run: |
          pip3 install setuptools
          pip3 install .[dev]

      - name: Run wrapper and integration tests
        run: |
          python3 build.py --update-wrapper --test-integration
  # build-wrapper-macos:
  #   runs-on: macos-latest
  #   strategy:
  #     matrix:
  #       python-version: [3.7] #[3.5, 3.6, 3.7, 3.8, 3.9]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install package
  #       run: |
  #         pip3 install setuptools
  #         pip3 install .[dev]
  #     - name: Build wrapper
  #       run: |
  #         python3 build.py --update-wrapper
  #     - name: Run integration tests
  #       run: |
  #         python3 build.py --test-integration
