name: Build and update wrappers

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-wrapper-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7] #[3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install python packages
        run: |
          pip install setuptools
          pip install .[protobuf-schema-generation,python-backend]
          pip install --upgrade protobuf
      - name: Build wrapper
        run: |
          python build.py --update-wrapper
      - name: Update protobuf schemas
        run: |
          python build.py --update-schemas
      - name: run integration tests
        run: |
          python build.py --test-integration

      # ensure that win64 wrapper matches source code by commiting build result
      - name: commit win64 wrapper to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add tool/unifmu/resources/common/unifmu_binaries/win64/unifmu.dll
          git commit --allow-empty -m "Update wrapper for win64 platforms"
          git push

  build-wrapper-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7] #[3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install python packages
        run: |
          pip3 install setuptools
          pip3 install .[protobuf-schema-generation,python-backend]
          pip3 install --upgrade protobuf
      - name: Build wrapper
        run: |
          python3 build.py --update-wrapper
      - name: Update protobuf schemas
        run: |
          python3 build.py --update-schemas
      - name: run integration tests
        run: |
          python3 build.py --test-integration
      # ensure that linux64 wrapper matches source code by commiting build result
      - name: commit linux64 wrapper to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add tool/unifmu/resources/common/unifmu_binaries/linux64/unifmu.so
          git commit --allow-empty -m "Update wrapper for linux64 platforms"
          git push

  build-wrapper-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7] #[3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install python packages
        run: |
          pip3 install setuptools
          pip3 install .[protobuf-schema-generation,python-backend]
          pip3 install --upgrade protobuf
      - name: Build wrapper
        run: |
          python3 build.py --update-wrapper
      - name: Update protobuf schemas
        run: |
          python3 build.py --update-schemas
      - name: run integration tests
        run: |
          python3 build.py --test-integration

      # ensure that darwin64 wrapper matches source code by commiting build result
      - name: commit darwin64 wrapper to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add tool/unifmu/resources/common/unifmu_binaries/darwin64/unifmu.dylib
          git commit --allow-empty -m "Update wrapper for darwin64 platforms"
          git push
